### ISSUE TITLE
Rename-on-error doesn't always seem to work (again)

### ISSUE THREAD

**Issue by texttheater** [texttheater/produce#10]
This should reliably happen when Produce is interrupted. Here's an example where it didn't:

```
p264360@pales:~/sr2$ produce out/Tatoeba.dev.decoded5
INFO: rebuilding file out/Tatoeba.train.model1
    numtrex=$(wc -l out/Tatoeba.train.trex | cut -d ' ' -f 1)
    swipl -G20g -p boxer=ext/candc/src/prolog/boxer -p knowledge=ext/candc/src/prolog/boxer/knowledge -p lex=ext/candc/src/prolog/boxer/lex -p semlib=ext/candc/src/prolog/lib -p fsa=ext/fsa6/swi -p setup=x -l fsa.pl -l train.pl -g train:main -- -m out/Tatoeba.train.model0 out/Tatoeba.train.trex out/Tatoeba.train.grammar $((numtrex * (1 - 1))) > out/Tatoeba.train.model1 2> out/Tatoeba.train.model1.log
^CERROR: interrupted
^CException ignored in: <module 'threading' from '/net/aps/64/opt/Python-3.4/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/net/aps/64/opt/Python-3.4/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/net/aps/64/opt/Python-3.4/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/net/aps/64/opt/Python-3.4/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
p264360@pales:~/sr2$
```

First need to find out why an exception was ignored, that looks like a red flag.

**Comment by texttheater** [comment]
Fixed (as good as can be, I think) in dc67d930416968b5cfe0fa547d882e714e27eac4.
