### ISSUE TITLE
Multiple import in prelude fail

### ISSUE THREAD

**Issue by Evpok** [texttheater/produce#46]
Testcase:

```
[]
prelude =
    import pathlib
    import shutil

[echo]
type = task
recipe = echo "spam"
```

Run `produce echo`.

Fails with:

```
Traceback (most recent call last):
  File "[...]produce", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "[...]/produce", line 959, in <module>
    produce(None)
  File "[...]/produce", line 928, in produce
    exec(globes.get('prelude', ''), globes)
  File "<string>", line 2
    import shutil
    ^
```

I'm investigating :-)

**Comment by texttheater** [comment]
Fixed in b9994b1da4cc8029326a8189d4192227c25e78f8.
